### ISSUE TITLE
Review and refactor existing code to be more conformed to Ansible way

### ISSUE THREAD

**Issue by droideck** [389ds/ansible-ds#16]
This issue is a place for discussion that can be referred to in the future.
And if we'll decide that everything is correct already, we can close it.

We need to make sure that we do things correctly from the beginning.

First, each developer can look and read through the best practices and guides posted here:

* upstream development - https://linux-system-roles.github.io/contribute.html
* role development - https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#roles
* module development - https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html
* recommended practices - https://github.com/redhat-cop/automation-good-practices

Then we can decide if we need to refactor anything and how it can be achieved. 
Personally, after I finish reading, I'll suggest improvements that can be discussed here.

**Comment by progier389** [comment]
Seems good.
But before doing the review I propose to merge [PR 17](https://github.com/389ds/ansible-ds/pull/17) so:
- there will be no pending work in progress when starting the review
- review will be done with latest Readme versions ...

**Comment by progier389** [comment]
I think that we can close this old one as the architecture was redesigned.
