### ISSUE TITLE
Add support for ini file to be able to run unit_tests in dev environment

### ISSUE THREAD

**Issue by progier389** [389ds/ansible-ds#6]
allow to have an ini file in $HOME to be able to successfully run the test in development environment as a non root user
The issue is that ansible-test reset most environment variable 

The ini file is used to specify:
   PREFIX: the directory server installation prefix
   LIB389PATH: where to search for the python lib389 library  
   DEBUGGING: (optionnal) to turn on the verbose mode 

The ini section is used to determine if its options is used for a given test:
 section names are absolute path 
and the  longest path that matches the start of the test path is the one taken in account.

Note: this issue depends on issue #3

**Comment by droideck** [comment]
@progier389  I think we can close it? What do you think?
